services:
    ubuntu:
        public: true
        container_name: vzletzx
        image: imlala/ubuntu-xfce-vnc-novnc:latest
        shm_size: "3gb"
        ports:
            - 6080:6080
        environment: 
            - VNC_PASSWD=passwd
            - GEOMETRY=1080x720
            - TZ=Asia/Shanghai
            - DEPTH=24
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 1000m
          memory: 3072Mi
          storage:
            size: 4Gi
            class: standard
